### ISSUE TITLE
Support GKE startup taints

### ISSUE THREAD

**Issue by raphaelfff** [nestybox/sysbox-pkgr#117]
https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler#startup_taints

To help with the autoscaler, it would be useful to add support for custom tains in the deploy-k8s.sh script

**Comment by ctalledo** [comment]
Thanks @raphaelfff for the suggestion.

In case you have cycles and want to implement this / contribute it, here's the relevant part of the code:
